Repository Kernel360/KBE5-Thisway-FE, pull requests merged in 2025-06, with the labels that each got.

#12 feat: #11 JWT 받는 방식 변환
  src/utils/api.js
Labels: enhancement

#13 사이드바 디자인 적용 및 공통 테마 설정
  index.html
  package-lock.json
  package.json
  src/App.jsx
  src/assets/default-profile.png
  src/assets/logo.png
  src/components/Sidebar.jsx
  src/theme/globalStyles.js
  src/theme/index.js
  src/theme/palette.js
Labels: enhancement

#14 Feat/7
  src/components/CarRegistrationModal.jsx
  src/pages/company/CompanyCarManagementPage.jsx
Labels: documentation

#15 feat: #10 업체용 차량 상세보기 페이지 구현
  src/App.jsx
  src/components/Sidebar.jsx
  src/pages/company/CompanyCarDetailPage.jsx
  src/theme/globalStyles.js
  src/theme/index.js
  src/theme/styledGlobalStyle.js
Labels: enhancement

#25 Refactor/16
  src/pages/admin/AdminUserManagementPage.jsx
  src/pages/company/CarRegistrationModal.jsx
  src/pages/company/CompanyCarManagementPage.jsx
  src/pages/company/CompanyUserManagementPage.jsx
  src/theme/styledGlobalStyle.js
Labels: refactor

#31 Refactor/30
  package-lock.json
  package.json
  src/pages/admin/AdminCompanyRegisterModal.jsx
  src/pages/admin/AdminManagementPage.jsx
  src/pages/admin/AdminUserRegisterModal.jsx
  src/pages/admin/CompanySearchModal.jsx
  src/pages/company/CompanyCarManagementPage.jsx
  src/pages/company/CompanyUserManagementPage.jsx
  src/theme/styledGlobalStyle.js
Labels: refactor

#32 Refactor/30
  src/pages/admin/AdminCompanyRegisterModal.jsx
  src/pages/admin/AdminManagementPage.jsx
  src/pages/admin/AdminUserRegisterModal.jsx
  src/pages/company/CompanyUserManagementPage.jsx
  src/pages/company/CompanyUserRegisterModal.jsx
Labels: refactor

#36 CompanySearchModal.jsx API 수정
  src/pages/admin/CompanySearchModal.jsx
Labels: bug

#38 차량 등록 로직 변경
  src/pages/company/CarModelSearchModal.jsx
  src/pages/company/CarRegistrationModal.jsx
  src/pages/company/CompanyCarDetailPage.jsx
  src/pages/company/CompanyCarManagementPage.jsx
  src/pages/company/CompanyCarRegistrationModal.jsx
  src/pages/company/CompanyUserManagementPage.jsx
  src/pages/company/CompanyUserRegisterModal.jsx
  src/utils/dateUtils.js
  src/utils/mapUtils.js
Labels: enhancement, refactor

#42 사이드바 프로필 관련 UI 수정, 로그아웃 기능 추가
  src/components/Sidebar.jsx
Labels: enhancement

#46 feat: #45 운행 일지 관련 페이지 생성
  src/assets/Current Minimal.png
  src/assets/end-marker.png
  src/assets/start-marker.png
  src/components/Button.jsx
  src/pages/company/CompanyCarDetailPage.jsx
  src/pages/trip/TripDetailViewPage.jsx
  src/pages/trip/TripHistoryPage.jsx
  src/utils/dateUtils.js
  src/utils/mapUtils.js
Labels: enhancement

#51 대시보드 차량 리스트, 지도 띄우기
  src/components/DashboardKakaoMap.jsx
  src/pages/company/CompanyDashboardPage.jsx
Labels: enhancement

#53 feat: #52 통계 및 대시보드 페이지 생성 및 디자인 적용
  package-lock.json
  package.json
  src/assets/Activity.png
  src/assets/Calendar.png
  src/assets/Clock.png
  src/assets/bar_chart_button.png
  src/assets/car.png
  src/assets/line_chart_button.png
  src/assets/rank_badge_1.png
  src/assets/rank_badge_2.png
  src/assets/rank_badge_3.png
  src/assets/settings.png
  src/assets/white-car.png
  src/components/Sidebar.jsx
  src/pages/company/CompanyCarRegistrationModal.jsx
  src/pages/company/CompanyDashboardPage.jsx
  src/pages/company/CompanyStatisticsPage.jsx
  src/pages/company/CompanyUserManagementPage.jsx
  src/pages/trip/TripHistoryPage.jsx
  src/theme/palette.js
  src/theme/styledGlobalStyle.js
Labels: enhancement

#56 업체 관리자 대시보드 페이지 수정
  src/components/DashboardKakaoMap.jsx
  src/pages/company/CompanyDashboardPage.jsx
Labels: refactor

#72 애뮬레이터 GPS 로그 수집 BE 변경사항 반영
  src/pages/emulator/EmulatorPage.jsx
Labels: enhancement
